### ISSUE TITLE
CRL Verification

### ISSUE THREAD

**Issue by ou7sid3r** [Azure-Samples/cognitive-services-speech-sdk#450]
Hi, I'm trying to use the Java SDK behind a corporate proxy. The server certificate that gets issued by our internal CA for connecting to westus.stt.speech.microsoft.com does not have the CRL URI info so the handshake fails when trying to recognize speech.

Is there a way to turn off CRL validation on the config? This is a snippet of the stacktrace from the recognition logs:
```
(768): 13512ms SPX_TRACE_INFO: AZ_LOG_INFO:  transport.cpp:1209 Start network check westus.stt.speech.microsoft.com
(768): 13512ms SPX_TRACE_INFO: AZ_LOG_INFO:  transport.cpp:1217 TransportDoWork: open transport.
(768): 13512ms SPX_TRACE_INFO: AZ_LOG_INFO:  transport.cpp:763 Start to open websocket. TransportRequest: 0xf8023210, wsio handle: 0xf8023980
(768): 13512ms SPX_TRACE_INFO: AZ_LOG_INFO:  tlsio_openssl.c:1946 create_openssl_instance by TLSv1_2_method.
(768): 14857ms SPX_TRACE_INFO: AZ_LOG_INFO:  tlsio_openssl.c:1604 No CRL distribution points defined on non self-issued cert, CRL check may fail.
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.0
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.1
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.2
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.3
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.4
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.5
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.6
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.7
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.8
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1267 could not read file /tmp/d7a79b8c.crl.9
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl Line:1267
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1569 No CRL dist point qualified for downloading.
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_crl_crldp Line:1569
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1612 Unable to retrieve CRL, CRL check will fail.
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:crls_http_cb Line:1612
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:681 SSL handshake failed: 5
(768): 14857ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:681
(768): 14857ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2376 FORCE-Closing tlsio instance.
```

**Comment by BrianMouncer** [comment]
This issue came up one another time, with a third party proxy server that used incomplete certificate. At the time, we reviewed the issue with our security team, and the feedback was “completely disabling the CRL checks would be a bad practice that we should not encourage by adding such a disable switch".  The best approch is to fix the certificate to include a CRL URI.

I would like to know more details of your specific case, and see if there is anything else we can do to help you out, but I don’t want to have a detailed security vulnerabilities discussion on GitHub, or ask you to expose your person email information in a public forum.

Can you please open an azure support ticket related to your question, and include more details of your situation, and private contact information?  Make sure you indicate this is “Technical” issue with “Cognitive Service” and the “Speech Client SDK”. Provide a summary of your situation and a way to contact you. 

https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest

Thanks,

Brian.

**Comment by jhakulin** [comment]
Closing this from here and continuation happens through Azure support
